# Generated by Django 4.0 on 2024-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cover',
            field=models.ImageField(upload_to='Customer/profile/coverPic/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(upload_to='Customer/profile/profilePic/'),
        ),
    ]
