# Generated by Django 4.0 on 2024-01-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_cover_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cover',
        ),
    ]
